#pragma once

#include "radio/radio_setup.hh"

#include "controller/controller.hh"

// GENERATED FILES
// These files are generated by the build.rs script on ./sys project
// and are used to provide a safe interface to the C++ code, using the bindgen crate
// We use a mix of C++ and Rust, where some libs on C++ will be reexported to Rust and used on the Rust code
// and then the Rust code will generate the C++ code to be used on the C++ code.

// Gamepad will provide a safe data structure to be used
#include "generated/gamepad.rs.h"
// Packet will provide a safe data structure to be used
#include "generated/packet.rs.h"